---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: splunk/universalforwarder
    command: no-provision
provisioner:
  name: ansible
verifier:
  name: testinfra
  options:
    junit-xml: ../../../../tests/results/uf-default-results.xml
