---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: splunk-uf-centos8
    image: geerlingguy/docker-centos8-ansible:latest
    pre_build_image: true
    command: "/lib/systemd/systemd"
    volumes:
      - "/opt/splunkforwarder/var"
  - name: splunk-uf-debian10
    image: jgeusebroek/debian10-molecule:latest
    pre_build_image: true
    command: "/lib/systemd/systemd"
    volumes:
      - "/opt/splunkforwarder/var"
  - name: splunk-uf-debian9
    image: geerlingguy/docker-debian9-ansible:latest
    pre_build_image: true
    command: "/lib/systemd/systemd"
    volumes:
      - "/opt/splunkforwarder/var"
  - name: splunk-uf-redhat8
    image: geerlingguy/docker-ubi8-ansible:latest
    pre_build_image: true
    command: "/lib/systemd/systemd"
    volumes:
      - "/opt/splunkforwarder/var"
provisioner:
  name: ansible
  env:
    ANSIBLE_HASH_BEHAVIOUR: merge
  inventory:
    links:
      hosts: ../../../../tests/fixtures/molecule-uf-hosts.yml
      group_vars: ./group_vars/
verifier:
  name: testinfra
  options:
    junit-xml: ../../../../tests/results/uf-default-results.xml
