---
- name: Create a dependency file
  file:
    path: /usr/share/man/man1
    state: directory
  when:
    - ansible_distribution == 'Debian'
  become: yes
  become_user: "{{ privileged_user }}"

- name: Install the JDK
  apt:
    name: openjdk-8-jdk-headless
    state: present
    update_cache: yes
  when:
    - ansible_distribution == 'Debian'
    - "'10' not in ansible_distribution_version"
  become: yes
  become_user: "{{ privileged_user }}"

- name: Install JDK dependencies
  apt:
    name: ['apt-transport-https', 'ca-certificates', 'wget', 'dirmngr', 'gnupg', 'software-properties-common']
    update_cache: yes
  when:
    - ansible_distribution == 'Debian'
    - "'10' in ansible_distribution_version"
  become: yes
  become_user: "{{ privileged_user }}"

- name: Get the openjdk apt key
  shell: |
    set -o pipefail
    wget -qO - https://adoptopenjdk.jfrog.io/adoptopenjdk/api/gpg/key/public | apt-key add -
  args:
    executable: /bin/bash
    warn: false
  when:
    - ansible_distribution == 'Debian'
    - "'10' in ansible_distribution_version"
  become: yes
  become_user: "{{ privileged_user }}"

- name: Get the key
  command: "add-apt-repository --yes https://adoptopenjdk.jfrog.io/adoptopenjdk/deb/"
  when:
    - ansible_distribution == 'Debian'
    - "'10' in ansible_distribution_version"
  become: yes
  become_user: "{{ privileged_user }}"

- name: Install openjdk
  apt:
    name: "adoptopenjdk-8-hotspot"
    update_cache: yes
  when:
    - ansible_distribution == 'Debian'
    - "'10' in ansible_distribution_version"
  become: yes
  become_user: "{{ privileged_user }}"

- name: Create splunk-launch.conf
  become: yes
  become_user: "{{ privileged_user }}"
  command: cp {{ splunk.home }}/etc/splunk-launch.conf.default {{ splunk.home }}/etc/splunk-launch.conf
  ignore_errors: true
  when:
    - ansible_distribution == 'Debian'

- name: Get JAVA_HOME
  shell: 'readlink -f /usr/bin/java | sed "s:bin/java::"'
  register: java_home
  become: yes
  become_user: "{{ privileged_user }}"
  ignore_errors: true
  when:
    - ansible_distribution == 'Debian'

- name: Set JAVA_HOME in splunk-launch.conf
  become: yes
  become_user: "{{ privileged_user }}"
  lineinfile:
    path: "{{ splunk.home }}/etc/splunk-launch.conf"
    regexp: '^JAVA_HOME'
    line: "JAVA_HOME={{ java_home.stdout }}"
  ignore_errors: true
  when:
    - ansible_distribution == 'Debian'