---
- name: Download the Java distribution
  get_url:
    url: "https://download.java.net/openjdk/jdk9/ri/jdk-9+181_windows-x64_ri.zip"
    dest: /opt/container_artifact/
    timeout: 30
    mode: 0666
  register: download_result
  until: download_result.status_code == 200

- name: Unzip the Java distribution
  unarchive:
    src: "/opt/container_artifact/jdk-9+181_windows-x64_ri.zip"
    dest: /opt/container_artifact/

- name: Create symlinks for java/javac
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  with_items:
    - { "src": "/opt/container_artifact/java-se-9-ri/jdk-9/bin/java.exe", "dest": "/usr/bin/java"}
    - { "src": "/opt/container_artifact/java-se-9-ri/jdk-9/bin/javac.exe", "dest": "/usr/bin/javac"}
  become: yes
  become_user: root
  ignore_errors: true

- name: Set JAVA_HOME in splunk-launch.conf
  become: yes
  become_user: "{{ privileged_user }}"
  lineinfile:
    path: "{{ splunk.home }}/etc/splunk-launch.conf"
    regexp: '^JAVA_HOME'
    line: "JAVA_HOME=/opt/container_artifact/java-se-9-ri/jdk-9"
    owner: "SYSTEM"
    group: "SYSTEM"
    create: yes
