---
- name: Determine ITSI default apps
  set_fact:
    itsi_apps: ["DA-ITSI-APPSERVER", "DA-ITSI-DATABASE", "DA-ITSI-EUEM", "DA-ITSI-LB", "DA-ITSI-OS",
                "DA-ITSI-STORAGE", "DA-ITSI-VIRTUALIZATION", "DA-ITSI-WEBSERVER", "SA-ITOA", "SA-ITSI-ATAD",
                "SA-ITSI-CustomModuleViz", "SA-ITSI-MetricAD", "itsi", "splunk_app_infrastructure"]

- name: Remove ITSI apps from installed apps list
  set_fact:
    installed_apps: "{{ installed_apps | difference(itsi_apps) | unique }}"
