---
- name: Run default Splunk provisioning
  hosts: localhost
  gather_facts: true
  strategy: free
  environment: "{{ ansible_environment | default({}) }}"
  tasks:

    - block:
        - name: Execute pre-setup playbooks
          include_tasks: execute_adhoc_plays.yml
          vars:
            playbook: "{{ ansible_pre_tasks }}"
          when:
            - ansible_pre_tasks is defined
            - ansible_pre_tasks is not none
            - ansible_pre_tasks is match("^(http|https|file)://.*")

        - name: Provision role
          include_role:
            name: "{{ splunk.role }}"
          when:
            - splunk.role is defined

        - name: Execute post-setup playbooks
          include_tasks: execute_adhoc_plays.yml
          vars:
            playbook: "{{ ansible_post_tasks }}"
          when:
            - ansible_post_tasks is defined
            - ansible_post_tasks is not none
            - ansible_post_tasks is match("^(http|https|file)://.*")

        - name: Check all instances for required restarts
          include_tasks: ./roles/splunk_common/tasks/check_for_required_restarts.yml

        - name: Flush restart handlers
          meta: flush_handlers

      become: yes
      become_user: "{{ splunk.user }}"
