ansible_ssh_user: "splunk"
ansible_pre_tasks:
ansible_post_tasks:
ansible_environment: {}
retry_delay: 10
retry_num: 60
wait_for_splunk_retry_num: 150
shc_sync_retry_num: 300

config:
    max_retries: 3
    max_delay: 60
    max_timeout: 1200
    defaults_dir: C:\\tmp\\defaults
    baked: default.yml
    env:
        var: SPLUNK_DEFAULTS_URL
        headers:
        verify: True
    host:
        url:
        headers:
        verify: True

splunk:
    build_location:
    allow_upgrade: True
    tar_dir: "splunkforwarder"
    opt: &opt "/opt"
    home: &home !!python/object/apply:os.path.join [*opt, "splunkforwarder"]
    user: "SYSTEM"
    group: "SYSTEM"
    exec: !!python/object/apply:os.path.join [*home, "bin", "splunk.exe"]
    pid: !!python/object/apply:os.path.join [*home, "var", "run", "splunk", "splunkd.pid"]
    admin_user: "admin"
    root_endpoint:
    password:
    declarative_admin_password: False
    secret:
    pass4SymmKey:
    svc_port: 8089
    ssl:
        enable: True
        cert:
        password:
        ca:
    launch:
    set_search_peers: True
    s2s:
        enable: True
        port: 9997
        ssl: False
        cert:
        password:
        ca:
    dsp:
        enable: False
        server: forwarders.scp.splunk.com:9997
        cert:
        verify: False
        pipeline_name:
        pipeline_desc:
        pipeline_spec:
    appserver:
        port: 8065
    kvstore:
        port: 8191
    http_port: 8000
    http_enableSSL: 0
    http_enableSSL_cert:
    http_enableSSL_privKey:
    http_enableSSL_privKey_password:
    hec:
        enable: True
        port: 8088
        ssl: True
        token:
        cert:
        password:
    shc:
        secret:
        pass4SymmKey:
        label: "shc_label"
        replication_factor: 3
        replication_port: 9887
        deployer_push_mode:
    idxc:
        secret:
        pass4SymmKey:
        discoveryPass4SymmKey:
        label: "idxc_label"
        search_factor: 3
        replication_factor: 3
        replication_port: 9887
    multisite_replication_factor_origin: 2
    multisite_replication_factor_total: 3
    multisite_search_factor_origin: 1
    multisite_search_factor_total: 2
    license_master_url:
    cluster_master_url:
    auxiliary_cluster_masters: []
    search_head_captain_url:
    deployer_url:
    deployment_client:
        name:
    connection_timeout: 180
    enable_service: False
    disable_popups: False
    service_name:
    smartstore:
    app_paths:
        default: !!python/object/apply:os.path.join [*home, "etc", "apps"]
        shc: !!python/object/apply:os.path.join [*home, "etc", "shcluster", "apps"]
        idxc: !!python/object/apply:os.path.join [*home, "etc", "master-apps"]
        deployment: !!python/object/apply:os.path.join [*home, "etc", "deployment-apps"]
        httpinput: !!python/object/apply:os.path.join [*home, "etc", "apps", "splunk_httpinput"]

    es:
      ssl_enablement: "auto"
