---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: splunk-standalone-systemd-centos8
    image: geerlingguy/docker-centos8-ansible:latest
    pre_build_image: true
    tmpfs:
      - /run
      - /tmp
      - /sys/fs/cgroup/memory/system.slice/Splunkd.service
      - /sys/fs/cgroup/cpu/system.slice/Splunkd.service
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
    command: "/lib/systemd/systemd"
    env:
      http_proxy: "${http_proxy}"
      https_proxy: "${https_proxy}"
      no_proxy: "${no_proxy}"
provisioner:
  name: ansible
  log: true
verifier:
  name: testinfra
  options:
    junit-xml: ../../../../tests/results/uf-rpm-test-results.xml
