---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
  options:
    c: ../../.yamllint
platforms:
  - name: splunk_standalone-systemd-centos8
    image: geerlingguy/docker-centos8-ansible:latest
    pre_build_image: true
    tmpfs:
      - /run
      - /tmp
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
    command: "/lib/systemd/systemd"
    env:
      http_proxy: "${http_proxy}"
      https_proxy: "${https_proxy}"
      no_proxy: "${no_proxy}"
provisioner:
  name: ansible
  log: true
  lint:
    name: ansible-lint
    enabled: true
    options:
      x: ["204", "701"]
      force-color: true
scenario:
  name: systemd
verifier:
  name: testinfra
  lint:
    name: flake8
    options:
      ignore: E501
  options:
    junit-xml: ../../../../tests/results/uf-rpm-test-results.xml
