---
- name: Check current license group
  splunk_api:
    method: GET
    url: "/services/licenser/groups/Free?output_mode=json"
    cert_prefix: "{{ cert_prefix }}"
    username: "{{ splunk.admin_user }}"
    password: "{{ splunk.password }}"
    svc_port: "{{ splunk.svc_port }}"
    body_format: "form-urlencoded"
    status_code: "200,404"
    timeout: 10
    use_proxy: no
  register: check_free_lic
  changed_when: false
  no_log: "{{ hide_password }}"

- name: Activate free license
  splunk_api:
    method: POST
    url: "/services/licenser/groups/Free?output_mode=json"
    cert_prefix: "{{ cert_prefix }}"
    username: "{{ splunk.admin_user }}"
    password: "{{ splunk.password }}"
    svc_port: "{{ splunk.svc_port }}"
    body:
      is_active: 1
    body_format: "form-urlencoded"
    status_code: [200]
    timeout: 10
    use_proxy: no
  when: not check_free_lic.json.entry[0].content.is_active
