---
- include_tasks: licenses/enable_free_license.yml
  when: license | lower == "free"

- include_tasks: licenses/enable_forwarder_license.yml
  when: license | lower == "forwarder"

- include_tasks: licenses/add_wildcard_license.yml
  vars:
    licenses: "{{ license }}"
  when: '"*" in license'

- include_tasks: licenses/add_license.yml
  vars:
    lic: "{{ license }}"
  when:
    - license | lower != "free"
    - '"*" not in license'
