---
# TODO: Might be better to use synchronize here, but we'll need rsync installed
- name: "Copy installed apps to {{ dest }}"
  shell: "tar -c --exclude local {{ splunk.app_paths.default }}/{{ item }} | tar -x -C {{ dest }}"
  become: yes
  become_user: "{{ splunk.user }}"
  with_items: "{{ installed_apps }}"
  register: copy_app
  changed_when: copy_app.rc == 0
