---
# TODO: Might be better to use synchronize here, but we'll need rsync installed
# Copy everything over except local/app.conf because some apps are disabled after installation
- name: "Copy installed apps to {{ dest }}"
  shell:
    cmd: "set -o pipefail && tar -c --exclude=local/app.conf --exclude='*.pyc' --exclude='*__pycache__*' {{ item }} | tar -x -C {{ dest }}"
    chdir: "{{ splunk.app_paths.default }}"
    executable: /bin/bash
  become: yes
  become_user: "{{ splunk.user }}"
  with_items: "{{ apps }}"
  register: copy_app
  changed_when: copy_app.rc == 0
