---
- name: Disable installed apps
  command: "{{ splunk.exec }} disable app {{ item }} -auth {{ splunk.admin_user }}:{{ splunk.password }}"
  become: yes
  become_user: "{{ splunk.user }}"
  with_items: "{{ installed_apps }}"
  when: installed_apps is defined and installed_apps | length > 0
