---
# By default, splunkd responds on SSL - only update 'enableSplunkdSSL' if purposely disabled
- name: Enable Splunkd SSL
  ini_file:
    dest: "{{ splunk.home }}/etc/system/local/server.conf"
    section: sslConfig
    option: enableSplunkdSSL
    value: "false"
    state: "{{ 'absent' if splunk.ssl.enable else 'present' }}"
  when: "'enable' in splunk.ssl"
  become: yes
  become_user: "{{ splunk.user }}"

- name: Set Splunkd CA
  ini_file:
    dest: "{{ splunk.home }}/etc/system/local/server.conf"
    section: sslConfig
    option: sslRootCAPath
    value: "{{ splunk.ssl.ca }}"
  when: "'ca' in splunk.ssl and splunk.ssl.ca"
  become: yes
  become_user: "{{ splunk.user }}"

- name: Set Splunkd cert
  ini_file:
    dest: "{{ splunk.home }}/etc/system/local/server.conf"
    section: sslConfig
    option: serverCert
    value: "{{ splunk.ssl.cert }}"
  when: "'cert' in splunk.ssl and splunk.ssl.cert"
  become: yes
  become_user: "{{ splunk.user }}"

- name: Set Splunkd SSL password
  ini_file:
    dest: "{{ splunk.home }}/etc/system/local/server.conf"
    section: sslConfig
    option: sslPassword
    value: "{{ splunk.ssl.password }}"
  when: "'password' in splunk.ssl and splunk.ssl.password"
  changed_when: false
  become: yes
  become_user: "{{ splunk.user }}"
