---
- name: Enable the Splunk-to-Splunk port
  command: "{{ splunk.exec }} enable listen {{ splunk.s2s_port }} -auth {{ splunk.admin_user }}:{{ splunk.password }} --accept-license --answer-yes --no-prompt"
  become: yes
  become_user: "{{ splunk.user }}"
  register: enable_s2s_status
  changed_when: enable_s2s_status.rc == 0 and 'already exists' not in enable_s2s_status.stdout
  failed_when:
    - enable_s2s_status.rc !=0
    - "'already exists' not in enable_s2s_status.stderr"
  no_log: "{{ hide_password }}"
