---
- name: "Restrict permissions on splunk.key for Status"
  include_tasks: restrict_permissions.yml
  vars:
    file_path: "{{ item }}"
  with_items:
    - "{{ splunk.home }}/var/lib/splunk/kvstore/mongo/splunk.key"

- name: Get Splunk status
  command: "{{ splunk.exec }} status --accept-license --answer-yes --no-prompt"
  become: yes
  become_user: "{{ splunk.user }}"
  register: splunk_status
  changed_when: False
  failed_when: False
  ignore_errors: yes
