---
- name: "Setting service_name fact from config"
  set_fact:
    splunk_service_name: "{{ splunk.service_name }}"
  when:
    - "'service_name' in splunk"

- name: Set Splunk service name
  block:
    - name: Setting SplunkForwarder service
      set_fact:
        splunk_service_name: "SplunkForwarder.service"
      when:
        - ansible_system is match("Linux")
        - splunk_systemd
        - splunk.role == "splunk_universal_forwarder"

    - name: Setting Splunkd service
      set_fact:
        splunk_service_name: "Splunkd.service"
      when:
        - ansible_system is match("Linux")
        - splunk_systemd
        - splunk.role != "splunk_universal_forwarder"

    - name: Setting splunk service
      set_fact:
        splunk_service_name: "splunk"
      when:
        - ansible_system is match("Linux")
        - not splunk_systemd

    - name: Setting splunkforwarder Windows service
      set_fact:
        splunk_service_name: "splunkforwarder"
      when:
        - ansible_system is not match("Linux")
        - splunk.role == "splunk_universal_forwarder"

    - name: Setting splunkd Windows service
      set_fact:
        splunk_service_name: "splunkd"
      when:
        - ansible_system is not match("Linux")
        - splunk.role != "splunk_universal_forwarder"
  when:
    - splunk_service_name is not defined or not splunk_service_name
    - splunk.enable_service
