- name: Install Splunk (apt)
  apt:
    name: "{{{{ splunk.build_location }}}}"
    state: "{{{{ 'latest' if splunk_upgrade else 'present' }}}}"
  register: install_result
  until: install_result is succeeded
  retries: "{{ retry_num }}"
  delay: "{{ retry_delay }}"
  become: yes
  become_user: "{{ privileged_user }}"
