---
# Restarts may be required for the node to register as a search head.
# This is a pre-requisite for using the 'add cluster-master' command
- name: Flush restart handlers
  meta: flush_handlers

# https://docs.splunk.com/Documentation/Splunk/latest/Indexer/Configuremulti-clustersearch
# TODO: Should we support 'remove cluster-master'?
- name: Peer auxiliary cluster masters
  command: "{{ splunk.exec }} add cluster-master {{ item.url }} -secret '{{ item.pass4SymmKey }}' -auth '{{ splunk.admin_user }}:{{ splunk.password }}'"
  become: yes
  become_user: "{{ splunk.user }}"
  register: peer_aux_cluster_master
  until: peer_aux_cluster_master.rc == 0 or "already exists" in peer_aux_cluster_master.stderr
  changed_when: peer_aux_cluster_master.rc == 0
  failed_when: peer_aux_cluster_master.rc != 0 and "already exists" not in peer_aux_cluster_master.stderr
  with_items: "{{ splunk.auxiliary_cluster_masters }}"
  notify:
    - Restart the splunkd service
  no_log: "{{ hide_password }}"
