---
- name: "Create .ui_login"
  file:
    path: "{{ splunk.home }}/etc/.ui_login"
    state: touch
    modification_time: preserve
    access_time: preserve
  become: yes
  become_user: "{{ splunk.user }}"
