---
- name: "Create .ui_login"
  file:
    path: "{{ splunk.home }}/etc/.ui_login"
    state: touch
    owner: "{{ splunk.user }}"
    group: "{{ splunk.group }}"
    mode: 0660
  become: yes
  become_user: "{{ splunk.user }}"
