---
- name: "Check if {{ file_path }} exists"
  stat:
    path: "{{ file_path }}"
  register: file_stat
  become: yes
  become_user: "{{ splunk.user }}"
  changed_when: False
  failed_when: False

- name: "Restrict permissions on {{ file_path }}"
  file:
    mode: u+rw,g-rwx,o-rwx
    path: "{{ file_path }}"
  become: yes
  become_user: "{{ splunk.user }}"
  when: file_stat.stat.exists
