---
- name: Set the Splunk secret from splunk.secret
  copy:
    dest: "{{ splunk.home }}/etc/auth/splunk.secret"
    owner: "{{ splunk.user }}"
    group: "{{ splunk.group }}"
    mode: 0400
    content: "{{ splunk.secret }}"
  when:
    - splunk.secret is defined
    - splunk.secret is not none
  become: yes
  become_user: "{{ splunk.user }}"

- name: Set the Splunk secret from splunk.splunk_secret
  copy:
    dest: "{{ splunk.home }}/etc/auth/splunk.secret"
    owner: "{{ splunk.user }}"
    group: "{{ splunk.group }}"
    mode: 0400
    content: "{{ splunk.splunk_secret }}"
  when:
    - splunk.splunk_secret is defined
    - splunk.splunk_secret is not none
  become: yes
  become_user: "{{ splunk.user }}"

