---
- name: "Test basic https endpoint"
  uri:
    url: "https://127.0.0.1:{{ splunk.svc_port }}"
    method: GET
    validate_certs: false
    status_code: 200,404
    timeout: 10
    use_proxy: no
  register: ssl_enabled
  ignore_errors: true
  delay: "{{ retry_delay }}"
  retries: "{{ retry_num }}"
  failed_when: 'ssl_enabled.status == -1 and "SSL: WRONG_VERSION_NUMBER" not in ssl_enabled.msg'
  until: 'ssl_enabled.status == 200 or ssl_enabled.status == 404 or "SSL: WRONG_VERSION_NUMBER" in ssl_enabled.msg'

# If the https call failed, we will revert to http and continue REST with normal error handling
- name: "Set url prefix for future REST calls"
  set_fact:
    cert_prefix: "{% if ssl_enabled.status == 200 %}https{% else %}http{% endif %}"
