---
- name: Set appserver port
  ini_file:
    dest: "{{ splunk.home }}/etc/system/local/web.conf"
    section: settings
    option: "appServerPorts"
    value: "{{ splunk.appserver.port }}"
  become: yes
  become_user: "{{ splunk.user }}"
