---
- name: Reformat conf type
  set_fact:
    splunk:
      conf: "{{ splunk.conf | dict2items }}"
  when: splunk.conf is mapping

- include_tasks: set_config_file.yml
  vars:
    conf_file: "{{ item.key }}.conf"
    conf_directory: "{{ item.value.directory | default(splunk.home + '/etc/system/local', true) }}"
    conf_stanzas: "{{ item.value.content }}"
  with_items: "{{ splunk.conf }}"
