---
- name: Set KeyValueStore Port
  ini_file:
    dest: "{{ splunk.home }}/etc/system/local/server.conf"
    section: kvstore
    option: "port"
    value: "{{ splunk.kvstore.port }}"
  become: yes
  become_user: "{{ splunk.user }}"
