---
- name: Set splunk-launch.conf variables
  lineinfile:
    path: "{{ splunk.home }}/etc/splunk-launch.conf"
    regexp: "^{{ item.key }}"
    line: "{{ item.key }}={{ item.value }}"
    create: yes
  become: yes
  become_user: "{{ splunk.user }}"
  with_dict: "{{ splunk.launch }}"

- name: Fix splunk-launch.conf POSIX ACL mask (Windows)
  command: setfacl -m mask::rwx "{{ splunk.home }}/etc/splunk-launch.conf"
  become: yes
  become_user: "{{ privileged_user }}"
  when: ansible_system is match("CYGWIN*|Win32NT")
