---
- name: Set the Splunk secret
  copy:
    dest: "{{ splunk.home }}/etc/auth/splunk.secret"
    owner: "{{ splunk.user }}"
    group: "{{ splunk.group }}"
    mode: 0400
    content: "{{ splunk.secret }}"
  when:
    - splunk.secret is defined
    - splunk.secret
  become: yes
  become_user: "{{ splunk.user }}"
