---
- name: "Get Splunk status"
  command: "{{ splunk.exec }} status --accept-license --answer-yes --no-prompt"
  become: yes
  become_user: "{{ splunk.user }}"
  register: splunk_status
  changed_when: False
  failed_when: False
  ignore_errors: yes

- name: "Stop Splunk via cli"
  command: "{{ splunk.exec }} stop --accept-license --answer-yes --no-prompt"
  become: yes
  become_user: "{{ splunk.user }}"
  register: stop_splunk
  changed_when: stop_splunk.rc == 0
  when:
    - not splunk.enable_service
    - splunk_status.rc == 0

- name: "Stop Splunk via systemctl"
  service:
    name: "{{ splunk_service_name }}"
    state: stopped
  when:
    - splunk.enable_service
    - splunk_status.rc == 0
    - ansible_system is match("Linux")
  become: yes
  become_user: "{{ privileged_user }}"

- name: "Stop Splunk via Windows service"
  win_service:
    name: splunkd
    state: stopped
  when:
    - splunk.enable_service
    - splunk_status.rc == 0
    - ansible_os_family == "Windows"
