---
- include_tasks: ../../../roles/splunk_common/tasks/install_apps.yml
  vars:
    app_url: "{{ item }}"
  loop: "{{ splunk.apps_location }}"

- include_tasks: ../../../roles/splunk_common/tasks/find_installed_apps.yml

- include_tasks: ../../../roles/splunk_common/tasks/copy_installed_apps.yml
  vars:
    apps: "{{ installed_apps }}"
    dest: "{{ splunk.app_paths.deployment }}"

- include_tasks: ../../../roles/splunk_common/tasks/disable_installed_apps.yml
