---
- name: Prepare
  hosts: all
  tasks:
    - name: Check splunk user
      user:
        name: splunk
        password: "*"
        state: present
      become: true

    - name: Setup apt http proxy
      lineinfile:
        path: /etc/apt/apt.conf.d/proxy.conf
        regexp: '^Acquire::http::Proxy '
        line: "Acquire::http::Proxy \"{{ lookup('env','http_proxy') }}\";"
        create: true
      when:
        - "lookup('env','http_proxy') is defined"
        - "lookup('env','http_proxy')  | length > 0"

    - name: Setup apt https proxy
      lineinfile:
        path: /etc/apt/apt.conf.d/proxy.conf
        regexp: '^Acquire::https::Proxy '
        line: "Acquire::https::Proxy \"{{ lookup('env','https_proxy') }}\";"
        create: true
      when:
        - "lookup('env','http_proxy') is defined"
        - "lookup('env','http_proxy')  | length > 0"

    - name: Check packages
      apt:
        name:
          - procps
          - curl
          - net-tools
        update_cache: yes
        state: latest
