---
splunk:
  role: splunk_universal_forwarder
  conf:
    - key: user-prefs
      value:
        directory: /opt/splunkforwarder/etc/users/admin/user-prefs/local
        content:
          general:
            default_namespace: appboilerplate
            search_syntax_highlighting: dark
  enable_service: true
  hec:
    token: abcd1234
  password: helloworld
