---

- name: Enable splunktcp-ssl input
  ini_file:
    dest: "{{ splunk.home }}/etc/system/local/inputs.conf"
    section: "splunktcp-ssl:{{ splunk.s2s_port if splunk.s2s_port is defined else splunk.s2s.port }}"
    option: "disabled"
    value: "0"
  register: splunktcp_ssl_enabled
  become: yes
  become_user: "{{ splunk.user }}"

- name: Remove splunktcp input
  ini_file:
    dest: "{{ splunk.home }}/etc/system/local/inputs.conf"
    section: "splunktcp://{{ splunk.s2s_port if splunk.s2s_port is defined else splunk.s2s.port }}"
    state: absent
  register: splunktcp_disabled
  become: yes
  become_user: "{{ splunk.user }}"

- name: Configure SSL certificate path
  ini_file:
    dest: "{{ splunk.home }}/etc/system/local/inputs.conf"
    section: SSL
    option: serverCert
    value: "{{ splunk.s2s.cert }}"
  register: splunktcp_ssl_cert_configured
  become: yes
  become_user: "{{ splunk.user }}"

- name: Configure SSL password
  ini_file:
    dest: "{{ splunk.home }}/etc/system/local/inputs.conf"
    section: SSL
    option: sslPassword
    value: "{{ splunk.s2s.password }}"
  register: splunktcp_ssl_pass_configured
  become: yes
  become_user: "{{ splunk.user }}"

- name: Configure SSL root CA
  ini_file:
    dest: "{{ splunk.home }}/etc/system/local/inputs.conf"
    section: SSL
    option: rootCA
    value: "{{ splunk.s2s.ca if splunk.s2s.ca else '$SPLUNK_HOME/etc/auth/cacert.pem' }}"
  when: ansible_system is not match("CYGWIN*|Win32NT")
  register: splunktcp_ssl_ca_configured
  become: yes
  become_user: "{{ splunk.user }}"

# Restart only when Splunk is running and when any of the above have changed
- include_tasks: trigger_restart.yml
  when: splunktcp_disabled is changed or splunktcp_ssl_cert_configured is changed or splunktcp_ssl_pass_configured is changed or splunktcp_ssl_ca_configured is changed
